plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs9.github.io
baseurl: "/s24-ykk"

course: "CS 9"
qtr: "S24"
instructor: "Prof K" 
quarter: "Spring 2024"
piazza_url: https://piazza.com/class/luithvjh3op3qg/
gradescope_url: https://www.gradescope.com/courses/762356/assignments

github_url: https://github.com/ucsb-cs9/s24-ykk

start_week: 1
start_date: 2024-03-31 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/academic-calendars
# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/registration-pass-dates

# TODO: make sure that the exam dates are correct on the syllabus as well!
#  https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/final-examinations
cal_dates: >                                                                    
  [                                                                            
    {"label":"S24 1st day of instruction", "date":"2024-04-01" },
    {"label":"Academic Integrity Contract Due", "date":"2024-04-09" },
    {"label":"S24 deadline to drop courses", "date":"2024-04-26" },
    {"label":"S24 CS 9 MIDTERM (3:30pm - 4:45pm)", "date":"2024-05-02" }, 
    {"label":"Holiday: Memorial Day", "date":"2024-05-27" },
    {"label":"S24 instruction ends", "date":"2024-06-07" },
    {"label":"S24 CS 9 FINAL (4:00pm - 6:00pm)", "date":"2024-06-13" }, 
    {"label":"S24 qtr ends", "date":"2024-06-14" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
